# Generated by Django 3.1.4 on 2020-12-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201205_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Product',
        ),
    ]
