name: foodgram

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Lint with flake8
#      run: flake8 . --config=setup.cfg

#    - name: Test with UnitTest
#      run: python manage.py test

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: korsakovpv/foodgram_project:latest

      - name: Install dump-env and create .env
        env:
          SECRET_DB_ENGINE: ${{ secrets.DB_ENGINE }}
          SECRET_DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          SECRET_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SECRET_DB_HOST: ${{ secrets.DB_HOST }}
          SECRET_DB_PORT: ${{ secrets.DB_PORT }}
          SECRET_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          export PATH="${PATH}:/home/runner/.local/bin"
          python -m pip install --upgrade pip
          pip install dump-env==1.2.0
          dump-env --template=.env.template --prefix='SECRET_' > .env
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
#          source: './.env, nginx/default.conf, ./docker-compose.yaml'
#          target: '/home/code'